# Generated by Django 5.2.17 on 2026-08-16 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0003_jobapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekerprofile',
            name='aadhaar',
            field=models.FileField(blank=True, null=True, upload_to='aadhaar/'),
        ),
    ]
