# Generated by Django 5.2.17 on 2026-08-19 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0005_jobseekerprofile_headline_jobseekerprofile_linkedin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='end_date',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
