# Generated by Django 5.2.17 on 2026-08-20 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0006_alter_experience_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('applied', 'Applied'), ('shortlisted', 'Shortlisted'), ('hired', 'Hired'), ('rejected', 'Not selected')], default='applied', max_length=20),
        ),
    ]
