# Generated by Django 5.2.17 on 2026-08-21 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0007_alter_jobapplication_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobapplication',
            options={'ordering': ['-applied_at']},
        ),
        migrations.RemoveConstraint(
            model_name='jobapplication',
            name='unique_jobseeker_job_application',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='jobseeker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_applications', to='jobseeker.jobseekerprofile'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('APPLIED', 'Applied'), ('UNDER REVIEW', 'Under Review'), ('SHORTLISTED', 'Shortlisted'), ('INTERVIEW SCHEDULED', 'Interview Scheduled'), ('REJECTED', 'Rejected'), ('HIRED', 'Hired')], default='APPLIED', max_length=30),
        ),
    ]
