# Generated by Django 5.2.17 on 2026-08-21 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0008_alter_jobapplication_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobseekerprofile',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='jobseekerprofile',
            name='qualification',
        ),
    ]
