# Generated by Django 5.2.17 on 2026-09-03 05:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0009_remove_jobseekerprofile_experience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekerprofile',
            name='disability',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='disability_category',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='disability_certificate',
            field=models.FileField(blank=True, null=True, upload_to='disability_documents/'),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='disability_percentage',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='disability_type',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('ADMIN', 'Admin Notification'), ('APPLICATION', 'Application Status')], default='ADMIN', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('jobseeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='jobseeker.jobseekerprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
