# Generated by Django 5.2.17 on 2026-09-06 03:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0010_jobseekerprofile_disability_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='new_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('ADMIN', 'Admin Notification'), ('APPLICATION', 'Application Status'), ('PROFILE', 'Profile Update'), ('JOB', 'New Job')], default='ADMIN', max_length=20),
        ),
    ]
