# Generated by Django 5.2.17 on 2026-09-22 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0013_conversation_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='rejection_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='rejection_reason_type',
            field=models.CharField(blank=True, choices=[('SELECTED_ELSEWHERE', 'Selected for another position'), ('REQUIREMENTS_NOT_MATCHED', 'Requirements not matched'), ('POSITION_FILLED', 'Position filled'), ('HIRING_COMPLETED', 'Hiring process completed'), ('EMPLOYER_REJECTED', 'Rejected by employer'), ('OTHER', 'Other')], max_length=50, null=True),
        ),
    ]
