# Generated by Django 5.2.17 on 2026-08-19 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerprofile',
            name='authorization_letter',
            field=models.FileField(blank=True, null=True, upload_to='employer_documents/authorization/'),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='company_gst_certificate',
            field=models.FileField(blank=True, null=True, upload_to='employer_documents/gst/'),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='company_registration_certificate',
            field=models.FileField(blank=True, null=True, upload_to='employer_documents/registration/'),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='representative_position',
            field=models.CharField(blank=True, choices=[('director', 'Director'), ('ceo', 'CEO'), ('proprietor', 'Proprietor'), ('hr', 'HR'), ('manager', 'Manager'), ('authorized_person', 'Authorized Person'), ('other', 'Other')], max_length=30),
        ),
    ]
