# Generated by Django 5.2.17 on 2026-08-21 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0003_job_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='education_details',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='job',
            name='key_features',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='job',
            name='roles_responsibilities',
            field=models.TextField(blank=True, default=''),
        ),
    ]
