# Generated by Django 5.2.17 on 2026-08-21 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0005_job_maximum_experience_job_minimum_experience_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('live', 'Live'), ('closed', 'Closed')], default='draft', max_length=20),
        ),
    ]
