# Generated by Django 5.2.17 on 2026-08-21 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0006_alter_job_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('live', 'Live'), ('closed', 'Closed')], default='Live', max_length=20),
        ),
    ]
