# Generated by Django 5.2.17 on 2026-09-10 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0008_alter_job_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='is_disability_job',
            field=models.BooleanField(default=False),
        ),
    ]
